#!/bin/bash

# Student full name: Nuraddin Aghalarov
# Student ID: 200562351
# Assignment 1: System Report Script
# This script generates a system information report.

# Variables
hostname=$(hostname)
os_info=$(source /etc/os-release && echo "$NAME $VERSION")
uptime_info=$(uptime -p)
cpu_info=$(lshw -class processor | grep -m 1 'product' | awk -F: '{print $2}')
cpu_speed=$(lscpu | grep 'MHz' | awk '{print $3}')
ram_size=$(free -h | grep Mem: | awk '{print $2}')
disk_info=$(lsblk -d -o NAME,MODEL,SIZE)
video_card=$(lshw -class display | grep product | awk -F: '{print $2}')
fqdn=$(hostname -f)
host_ip=$(ip a | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')
gateway_ip=$(ip r | grep default | awk '{print $3}')
dns_server=$(grep 'nameserver' /etc/resolv.conf | awk '{print $2}')
network_card=$(lshw -class network | grep 'product' | awk -F: '{print $2}')
users_logged=$(who | awk '{print $1}')
disk_space=$(df -h | awk '$NF=="/"{print $4}')
process_count=$(ps aux | wc -l)
load_avg=$(uptime | awk -F'load average: ' '{print $2}')
memory_alloc=$(free -h | grep Mem: | awk '{print $3 " / " $2}')
listening_ports=$(ss -lnt)
ufw_rules=$(sudo ufw status)


cat <<EOF

System Report generated by $USER on $(date)

System Information
------------------
Hostname: $hostname
OS: $os_info
Uptime: $uptime_info

Hardware Information
--------------------
CPU: $cpu_info
Speed: $cpu_speed MHz
RAM: $ram_size
Disk(s): $disk_info
Video: $video_card

Network Information
-------------------
FQDN: $fqdn
Host Address: $host_ip
Gateway IP: $gateway_ip
DNS Server: $dns_server

InterfaceName: $network_card
IP Address: $host_ip

System Status
-------------
Users Logged In: $users_logged
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_avg
Memory Allocation: $memory_alloc
Listening Network Ports: $listening_ports
UFW Rules: $ufw_rules
